  in_dir: /content/kits_preprocessed
  out_dir: /content/kits19_predictions
  with_masks: True
  mode: segmentation
  checkpoint_path: resnet34unet_seg_tuonly2d2_381epochs_seed15_best.pth
  pseudo_3D: False

  io_params:
    test_size: 0.2
    split_seed: 15
    batch_size: 1
    num_workers: 2
    file_ending: .npy # nii.gz

  model_params:
    architecture: unet_smp
    # instance_norm: False
    # nnunet:
    #   input_channels: 1
    #   base_num_features: 30
    #   num_classes: 3
    #   num_pool: 5
    #   num_conv_per_stage: 2
    #   feat_map_mul_on_downscale: 2
    #   deep_supervision: False
    #   convolutional_pooling: True
    #   convolutional_upsampling: True
    #   max_num_features: 320
    # # 2D ONLY
    encoder: resnet34
    activation: sigmoid
    unet_smp:
      decoder_attention_type: ~ # scse
      classes: 1
      decoder_use_batchnorm: True # inplace for InplaceABN
    # fpn_smp:
    #   classes: 1
    #   dropout: 0.2

  predict_3D_params:
    do_mirroring: True
    num_repeats: 1
    use_train_mode: False
    batch_size: 1
    mirror_axes:
      - 0
      - 1
      # - 2
    tiled: True
    tile_in_z: True
    step: 2
    patch_size:
      - 256
      - 256
      # - 96
      # - 160
      # - 160
    regions_class_order:  # ~ #argmax
      - 0
      - 1
    use_gaussian: False
    pad_border_mode: edge
    pad_kwargs: {}
    all_in_gpu: False
